services:
  - type: web
    name: arcop-website
    env: python
    pythonVersion: "3.12.10"   # <-- ajoute cette ligne
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: arcop-db
          property: connectionString
    autoDeploy: true
